### ISSUE TITLE
world format question

### ISSUE THREAD

**Issue by boneskull** [Steffo99/lihzahrd#4]
Hi, found this project searching for descriptions of the `.wld` format.  I'm trying to teach myself Rust by parsing `.wld` files, and your project is very helpful, despite your comments that claim sections to be a mess :smile:

I don't know if you can answer this, but I'm trying to understand `tileframeimportant`. from some of the (old) linked documentation, it's explained as this:

> Finally, some tile types are marked "Important", and contain texture coordinates, other tiles have their texture coordinates calculated at runtime. Which types are important or not is not stored in the wld document, instead it is up to the client to keep a list.

I don't really understand this.  but looking at your code, is it correct to say that the  "important" designation only applies to blocks?  What's a texture coordinate?  

* * * 

One other thing: I notice in your string parsing routine, you're using ULEB128.  How did you determine this was the case?  Parsing the world name, it looks like you can get away with reading a byte for the string length (which, in my naive tests, can be no longer than 20), and then just taking this number of subsequent bytes for the string.  Is there another place where this strategy doesn't work?

**Comment by Steffo99** [comment]
Hello!

I'm glad this project is useful to someone other than [me](https://github.com/Steffo99/flyingsnake) :)

It also seems like a good idea to remake this in Rust, as `lihzahrd` currently is terribly slow (it takes around 1 minute to parse a small world 😕)...

Anyways:

-------------------

If I remember correctly, the `tileframeimportant` property is related to the texture rendering.

All blocks in Terraria have a spritesheet that looks like this:
![](https://i.imgur.com/s9ZtC9n.png)

For every placed block, Terraria must select a tile to draw from the spritesheet:
- some types of blocks, the **non-TileFrameImportant** ones, always use the same texture (such as bricks, wood, dirt, etc), so the tile to draw is selected a single time when the game is started;
- other blocks that have special interactions (such as torches that can be turned off with wire), animated blocks (living fire) or have multiple variants that use the same block id (tombstones, most furniture) are marked **TileFrameImportant**, so the tile to draw is selected every time a new frame is rendered, making animations possible.

I'm not really sure about the details, though... (perhaps try asking in the [tModLoader Discord](https://tmodloader.net/discord)?)

-------------------

![](https://gamepedia.cursecdn.com/terraria_gamepedia/5/5d/Sign.png?version=999b8b04f3a2c51e14045784e52dcb95)

About ULEB128... I [found out](https://github.com/Steffo99/lihzahrd/commit/4eefcc227bd3ed79385c615ce1acfc207454eb05) that all strings use that encoding while trying to parse the **content of signs** (that can be longer than 127 characters!) 

Sadly, I can't find any reference for that, or even remember _how_ I figured that out (probably a lot of messing around with the Python console), but I'm pretty sure it's the correct encoding for all strings in the file.

**Comment by boneskull** [comment]
This makes sense. thanks for getting back so quickly.

when I get as far as parsing the sign content, I'll see if I can confirm your findings.  

that said, I can't (yet) figure out how a world name would need this encoding; given a 20-char-length world name, the length is stored in the first byte, and the next 20 bytes contain the name (I can confirm this with a hex editor, where the name is not encoded).  see [Pascal strings](https://en.wikipedia.org/wiki/String_(computer_science)#Length-prefixed)

if I ever wind up having something to show for my efforts, I'll let you know when I've put it up (and give thanks in the readme).

**Comment by Steffo99** [comment]
For strings under 127 characters, ULEB and Pascal strings are equivalent :)
