### ISSUE TITLE
Not able to detect a enchanted sword tile

### ISSUE THREAD

**Issue by rodjjo** [Steffo99/lihzahrd#5]
When the tile is an enchanted sword tile.block and tile.extra is null

**Comment by Steffo99** [comment]
Hi! Thanks for your bug report!

Can you attach the world file that gave you this problem to this issue?

Generating a world with a enchanted sword may take a while, and I'm a bit busy nowadays...

If you sent it to me, it would make finding and fixing this problem a lot faster! :)

**Comment by rodjjo** [comment]
There is a enchanted sword at coordinate 351, 297 

[Casarao.zip](https://github.com/Steffo99/lihzahrd/files/4483517/Casarao.zip)

```python
world = lihzahrd.World.create_from_file("Casarao.wld")
print(f'{repr(world.tiles[(351, 297)])}')
```

**Comment by rodjjo** [comment]
I guess enchanted sword is a object https://terraria.gamepedia.com/Objects

**Comment by rodjjo** [comment]
[TerraMap](https://github.com/TerraMap/windows) is able to detect it.

**Comment by Steffo99** [comment]
I can confirm that this is a bug.

The block should show up as `BlockType.LARGE_PILES2`, but it currently shows up as `None`. Hmmm...

**Comment by Steffo99** [comment]
Wait, no, nevermind!

You're looking at the wrong coordinates :)

![](https://user-images.githubusercontent.com/1540885/79582242-ca5c8980-80cb-11ea-9f05-c93f7b6def97.png)

The sword is at (352, 297), and it appears correctly there :)

![](https://user-images.githubusercontent.com/1540885/79582321-e4966780-80cb-11ea-8f1f-769e22f0819d.png)
