### ISSUE TITLE
Check contents of chests

### ISSUE THREAD

**Issue by SouDescolado** [Steffo99/lihzahrd#7]
Hello! I am trying to make a python program to check every chest from the world. However, all I can get in return is, for example: `<Chest '' at 3145, 635>`. How do I convert this to return the items of the chest?

**Comment by Steffo99** [comment]
`Chest` objects have a `.contents` property you can access to get a list of their contents (as [`ItemStacks`](https://gh.steffo.eu/lihzahrd/html/chests.html#lihzahrd.chests.ItemStack) )! :)

### Example

```python
first_item_in_chest = chest.contents[0]
```
